AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend with a RESTful API endpoint using Amazon API Gateway.
# Parameters: 
#   TableNameParameter: 
#     Type: String
Resources:
  microservicehttpendpoint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler # js-file.method-name
      Runtime: nodejs20.x
      CodeUri: .
      Description: >-
        A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref TableNameParameter
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /users
            Method: ANY